# .github/workflows/deploy-production.yml

name: Deploy a Produccion

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version del release (ej. v1.2.3)'
        required: true

jobs:
  deploy-to-prod:
    runs-on: self-hosted
    environment: # Requiere aprobación manual
      name: production
      url: 127.0.0.1:8080

    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" > .env
          echo "DOCKERHUB_TOKEN=${{ secrets.DOCKERHUB_TOKEN }}" >> .env

      - name: Hacer backup de la base de datos
        run: ./scripts/backup.sh

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir y subir imagenes de Docker
        run: |
          docker compose -f docker-compose.prod.yml build
          docker compose -f docker-compose.prod.yml push

      - name: Ejecutar deployment script
        run: ./scripts/deploy.sh production

      - name: Health Check y Smoke Tests
        run: ./scripts/health-check.sh production

      - name: Notificar deployment exitoso
        run: |
          # Comando para enviar una notificacion a Slack, email, etc.
          echo "Deployment de version ${{ github.event.inputs.version }} a produccion exitoso."