name: Monitoreo Continuo de Produccion

on:
  schedule:
    - cron: '*/30 * * * *' # Cada 30 minutos

jobs:
  monitor:
    runs-on: self-hosted
    steps:
      - name: Ejecutar Health Check
        run: ./scripts/health-check.sh production